# Generated by Django 3.2.5 on 2021-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(max_length=2083),
        ),
    ]
