# Generated by Django 3.2.5 on 2021-07-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210721_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category_name',
        ),
    ]
