# Generated by Django 3.2.5 on 2021-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_book_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('amount', models.IntegerField(max_length=6)),
            ],
        ),
    ]
