# Generated by Django 3.2.5 on 2021-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='orderedOn',
            field=models.CharField(default='date', max_length=100),
        ),
    ]
